name: adobe_xd
description: Generate code for building apps with Flutter based on your designs in Adobe XD with the â€œXD to Flutterâ€ plugin. This package contains helper widgets used by the plugin.
repository: https://github.com/AdobeXD/xd-to-flutter-plugin/tree/master/adobe_xd
homepage: https://adobe.com/go/xd_to_flutter

version: 2.0.1

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=1.6.7'

dependencies:
  # collection: ^1.15.0
  collection: ^1.17.1
  flutter:
    sdk: 'flutter'
  # flutter_svg: ^1.0.3
  flutter_svg: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

